version: '3.2'
services:
  kafka1:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: INT://:9091,EXT://:9092
      KAFKA_ADVERTISED_LISTENERS: INT://:9091,EXT://192.168.13.41:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    networks:
    - cluster
    volumes:
    - /var/lib/kafka1/data:/var/lib/kafka/data
    ports:
    - 9092:9092

  kafka2:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: INT://:9091,EXT://:9092
      KAFKA_ADVERTISED_LISTENERS: INT://:9091,EXT://192.168.13.42:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    networks:
    - cluster
    volumes:
    - /var/lib/kafka2/data:/var/lib/kafka/data
    ports:
    - 9093:9092

  kafka3:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: INT://:9091,EXT://:9092
      KAFKA_ADVERTISED_LISTENERS: INT://:9091,EXT://192.168.13.43:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    networks:
    - cluster
    volumes:
    - /var/lib/kafka3/data:/var/lib/kafka/data
    ports:
    - 9094:9092

networks:
  cluster:
    external:
      name: cluster
