version: '3.2'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.2.1
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka3:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_DEBUG: "true"
    networks:
    - cluster
    ports:
    - 8081:8081
    deploy:
      placement:
        constraints:
        - node.labels.microservices_01 == true
      resources:
        limits:
          cpus: '0.50'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 512M

  schema-registry-ui:
    image: landoop/schema-registry-ui
    environment:
      PROXY: "true"
      SCHEMAREGISTRY_URL: http://schema-registry:8081
    ports:
    - "8300:8000"
    networks:
    - cluster
networks:
  cluster:
    external:
      name: cluster
